# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum_db
      MYSQL_USER: root
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/forum_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_TOKEN: secret_key
      SERVER_PORT: 443
      SERVER_KEY_ALIAS: local_ssl
      SERVER_KEY_PASSWORD: secret123

    steps:
    - name: Check test coverage
      uses: sysoiev/gha-clover-test-coverage-check@v1
      id: coverage
      with:
          percentage: "70"
    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v1
      id: badge
      with:
          label: 'Coverage'
          status: ${{ steps.coverage.outputs.coverage }}
          path: ./badges/test-coverage.svg
          color: ${{
            steps.coverage.outputs.coverage > 90 && 'green'              ||
            steps.coverage.outputs.coverage > 80 && 'yellow,green'       ||
            steps.coverage.outputs.coverage > 70 && 'yellow'             ||
            steps.coverage.outputs.coverage > 60 && 'orange,yellow'      ||
            steps.coverage.outputs.coverage > 50 && 'orange'             ||
            steps.coverage.outputs.coverage > 40 && 'red,orange'         ||
            steps.coverage.outputs.coverage > 30 && 'red,red,orange'     ||
            steps.coverage.outputs.coverage > 20 && 'red,red,red,orange' ||
            'red' }}
    - uses: actions/checkout@v2
    - name: Install redis
      run: sudo apt-get install -y redis-tools redis-server
    - name: Verify that redis is up
      run: redis-cli ping
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_ROOT_PASSWORD }}
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
